### ISSUE TITLE
Upgrade to TimescaleDB 2

### ISSUE THREAD

**Issue by GeorgeBark** [Expaso/hassos-addons#10]
I was wondering if there was a plan to upgrade de add-on to version 2.x.

I am no expert in add-ons but I have some SQL knowledge and will be happy to help if needed.

Thanks!

**Comment by expaso** [comment]
Hi @GeorgeBark ,

Yep, I am currently testing the next version based on postgresql 14 and Timescale 2.6.0.
Please stay tunes. I want to get this right, as not to break any exisiting setups..

**Comment by expaso** [comment]
As a starter, the new pgAdmin version just went live..

**Comment by expaso** [comment]
I'm closing this issue, because it's a duplicate of : https://github.com/Expaso/hassos-addon-timescaledb/issues/10
Please keep an eye on that one, because a new version will launch soon including timescale 2.6 and an auto-upgrade to postgresql 14.2.
