### ISSUE TITLE
pgadmin upgrade to 6

### ISSUE THREAD

**Issue by Kilowatt-W** [Expaso/hassos-addons#11]
Hello,

thanks for the nice addons. Maybe i could ask if there are plans to update timedb and pgadmin to the latest versions in near future ?

greetings from Austria

Kilowatt

**Comment by expaso** [comment]
Hi @Kilowatt-W , 

Thanks!
Yes, I am currently beta-testing an upgrade for this addon to PostgreSQL 14 and timescale 2.6..

It's a real PITA to get it all automatically upgraded, but it's looking good. Stay tuned, the new version will be released soon,
