### ISSUE TITLE
Postgres 14 update failing

### ISSUE THREAD

**Issue by snerdish** [Expaso/hassos-addons#15]
After installing the offered upgrade to timescaledb, postgresql doesn't start. Logs show the following:

Checking for presence of required libraries                 fatal
Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    loadable_libraries.txt
Failure, exiting
[13:48:44] ERROR: PostgreSQL could not upgrade! Please inspect any errors in the lines above!
[13:48:44] ERROR: Upgrade was not succesfull.
[cont-init.d] init.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by expaso** [comment]
What architecture are you on?
And: Is it possible for you to extract the **loadable_libraries.txt** file from the data directory?

I suspect there are some extensions in your setup that need a little bit of extra help.
Can you give me a list of extensions that you have in use?

**Comment by CommanderTux** [comment]
Hi,

I did have the same issue upgrading from 1.1.6 to version 2.0.0.
My  **loadable_libraries.txt** showed:

```
could not load library "$libdir/timescaledb-1.7.4": ERROR:  could not access file "$libdir/timescaledb-1.7.4": No such file or directory
In database: dsmrreader
```
I restored a backup and all was fine again. I will not update to this version 2.0.0

**Comment by expaso** [comment]
Hi @CommanderTux , 

Do you use the aarch64 (raspberry pi 4 / odroid) or the amd64 image (intel NUC / normal machines) architecture?

**Comment by CommanderTux** [comment]
Hi @Expaso ,

I use a intel NUC supervised install on Debian 11.

**Comment by expaso** [comment]
To streamline this process a bit, I'm closing this issue to continue on [#16](https://github.com/Expaso/hassos-addon-timescaledb/issues/16). They all seem related.

I will post my findings there, so it's not scattered around multiple issues.

**Comment by expaso** [comment]
@CommanderTux , @snerdish , please check #16 

The problem lies with the add-on configuration not having all timescale-enabled databases listed.
Please add all your timescale-enabled databases here and try the upgrade again please.

![image](https://user-images.githubusercontent.com/26247804/162153677-a15c194c-0c69-44e9-aefc-68903bd32dac.png)
