### ISSUE TITLE
Error updating TimescaleDB addon -> Docker Image ARMv7 missing.

### ISSUE THREAD

**Issue by regystro** [Expaso/hassos-addons#16]
"You have 1.1.6 installed. Click update to update to version 2.0.0". After clicking UPDATE;

_Can't install husselhans/hassos-addon-timescaledb-armv7:2.0.0: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=2.0.0&fromImage=husselhans%2Fhassos-addon-timescaledb-armv7&platform=linux%2Farm%2Fv7: Not Found ("manifest for husselhans/hassos-addon-timescaledb-armv7:2.0.0 not found: manifest unknown: manifest unknown")_

Running on a Raspberry Pi 3B
Operating System Raspbian GNU/Linux 10 (buster)
Docker version 20.10.3
Home Assistant core-2022.3.8 / supervisor-2022.03.5

**Comment by expaso** [comment]
I see that the 2.0.0 image for ARM v7 is not correctly uploaded to dockerhub.
Will look into this. Thank you for your issue!

**Comment by expaso** [comment]
Hi  @regystro , Here you go!

https://hub.docker.com/repository/docker/husselhans/hassos-addon-timescaledb-armv7

Please note that this version does an upgrade from Postgres 12 to Postgres 14. This can take a while, especially on a PI 3.
Please be patient and do not stop the addon by hand. It will restart itself  a few times when needed.

Also, make sure ALL your timescale enabled databases are listed in your config before upgrading, otherwise the upgrde process will fail:


![image](https://user-images.githubusercontent.com/26247804/162140927-5cd9c2d3-aae6-4939-b9e1-bb0142b122d8.png)

**Comment by regystro** [comment]
Hi @Expaso . Thank you, I'll try to upgrade later.

Regarding your advice, I don't have timescale enabled databases (only Postgres so far), so I guess it won't be a problem.

**Comment by regystro** [comment]
Oops:

```
2022-04-08 10:10:09.515 UTC [356] LOG:  database system is shut down
[12:10:09] NOTICE: Upgrading databases..
Performing Consistency Checks
-----------------------------
Checking cluster versions                                   ok
Checking database user is the install user                  ok
Checking database connection settings                       ok
Checking for prepared transactions                          ok
Checking for system-defined composite types in user tables  ok
Checking for reg* data types in user tables                 ok
Checking for contrib/isn with bigint-passing mismatch       ok
Checking for user-defined encoding conversions              ok
Checking for user-defined postfix operators                 ok
Creating dump of global objects                             ok
Creating dump of database schemas
  homeassistant
  postgres
  template1
                                                            ok
Checking for presence of required libraries                 fatal
Your installation references loadable libraries that are missing from the
new installation.  You can add these libraries to the new installation,
or remove the functions using them from the old installation.  A list of
problem libraries is in the file:
    loadable_libraries.txt
Failure, exiting
[12:10:28] ERROR: PostgreSQL could not upgrade! Please inspect any errors in the lines above!
[12:10:28] ERROR: Upgrade was not succesfull.
[cont-init.d] init.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

These are the contents of "loadable_libraries.txt":

```
could not load library "$libdir/timescaledb-1.7.4": ERROR:  could not access file "$libdir/timescaledb-1.7.4": No such file or directory
In database: homeassistant
```

**Comment by CommanderTux** [comment]
Hi @Expaso ,

You were correct. The -dsmrreader database was not listed under  'Timescale enabled'.

Thank you.

**Comment by regystro** [comment]
In my case this is what I got:

```
databases:
  - homeassistant
timescale_enabled: []
timescaledb:
  telemetry: 'off'
  maxmemory: 512MB
  maxcpus: '4'
max_connections: 20
system_packages: []
init_commands: []
```

No timescale_enabled databases because I only need Postgres. I'll try adding homeassistant db to timescale_enabled and will tell you the outcome.

Update: I can confirm that after adding homeassistant db to timescale_enabled, the upgrade was successful. Thank you.
