### ISSUE TITLE
Please upgrade TimescaleDB to 2.6.1

### ISSUE THREAD

**Issue by bjornbak** [Expaso/hassos-addons#17]
**Describe the bug**
Seeing a lot of 
```
2022-04-16 00:26:31.736 UTC [12438] LOG:  the "timescaledb" extension is not up-to-date
2022-04-16 00:26:31.736 UTC [12438] HINT:  The most up-to-date version is 2.6.1, the installed version is 2.6.0.
```
in the addon log.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by expaso** [comment]
Hi @bjornbak, 

These new versions keep coming! :) I'll try to keep up.
My first priority is to make sure everybody is succesful in upgrading to Postgresql 14.

**Comment by bjornbak** [comment]
> Hi @bjornbak,
> 
> These new versions keep coming! :) I'll try to keep up. My first priority is to make sure everybody is succesful in upgrading to Postgresql 14.

I had issues with pgsql 14 too.
Added 
```
init_commands:
  - >-
    sed -i "s/#password_encryption = md5/password_encryption = md5/"
    /data/postgres/postgresql.conf
```

**Comment by expaso** [comment]
Hi @bjornbak ,  can you elaborate on that last command further?
Why did you need to change the md5 enctryption?

**Comment by expaso** [comment]
Oh BTW, 

these messages
'
2022-04-16 00:26:31.736 UTC [12438] LOG:  the "timescaledb" extension is not up-to-date
2022-04-16 00:26:31.736 UTC [12438] HINT:  The most up-to-date version is 2.6.1, the installed version is 2.6.0.
'
are not fatal. 
I bump versions every half year or so. I'm trying to maintain a balance between stability and new versions / functions.

**Comment by bjornbak** [comment]
> Why did you need to change the md5 enctryption?

It is a long time ago but think the issue is the default is changed so I need to tell explicitly that I want md5.

**Comment by expaso** [comment]
Alright, a new releae is out!

Should this issue still persists, please reopen!
