### ISSUE TITLE
Paste from macOS clipboard not working within pgadmin SQL window

### ISSUE THREAD

**Issue by 42Network** [Expaso/hassos-addons#40]
**Describe the bug**
Paste from macOS clipboard not working within SQL window

**To Reproduce**
1. Launch pgadmin4
2. Open a SQL terminal window
3. Try to paste some text via Cmd-V or Right-click->Paste
4. Nothing happens

**Expected behavior**
Text should be pasted

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome and Firefox
 
I am unable to copy/paste the examples provided for setting up Timescale, such as the following. I've tried with both Chrome and Firefox. Pasting into other browser tabs, such as the Home Assistant SSH app, work just fine.

Any clues appreciated.

```
CREATE OR REPLACE FUNCTION public.isnumeric(
	text)
    RETURNS boolean
    LANGUAGE 'plpgsql'
    COST 100
    IMMUTABLE STRICT PARALLEL UNSAFE
AS $BODY$
DECLARE x NUMERIC;
BEGIN
    x = $1::NUMERIC;
    RETURN TRUE;
EXCEPTION WHEN others THEN
    RETURN FALSE;
END;
$BODY$;

ALTER FUNCTION public.isnumeric(text)
    OWNER TO postgres;
```

**Comment by expaso** [comment]
Hmm.. That is strange... On Windows at least it seams to work on my side, but that won't help you of course.

Can you perhaps try this:

1) Open-up the addon on a port on your homeassistant by setting a port in the configuration of the addon:

![image](https://github.com/Expaso/hassos-addons/assets/26247804/651f69e0-9c36-4912-a8e0-08ce19f18c98)

2) Access pgAdmin on that port by browsing to your homeassistant, given that specific port:

![image](https://github.com/Expaso/hassos-addons/assets/26247804/28e2d5a9-ee53-4d8b-930f-039746fc5da2)

It should load pgAdmin full-screen in the browser:

![image](https://github.com/Expaso/hassos-addons/assets/26247804/991d7ff1-860c-4fd8-a86d-8689982758e3)



Can you now use copy/paste?

**Comment by expaso** [comment]
Closing issue, marked as stale. 
Please reopen if still an issue.

**Comment by 42Network** [comment]
Hi. Thanks for the suggestion and sorry for the delay. I made mine look like yours, using port 12346, and saved and restarted pgAdmin (a few times). However, trying to browse to that new port( homeassistant:12346) fails, and when I use "Open Web UI" from within the pgAdmin Addon, it still opens pgAdmin at the default URL of homeassistant:8123/hassio/ingress/77b2833f_pgadmin4. Also, when I view the YAML version of the pgAdmin config, this new custom port is not mentioned. Somehow it isn't sticking...ideas?

Also, I'm slightly new to GitHub. Hope you see this comment. I don't see a way to reopen this issue now that it is closed. Should I open a new issue and link to this closed one?
