### ISSUE TITLE
Mirror set up to "learn" timescaledb

### ISSUE THREAD

**Issue by jjkoehorst** [Expaso/hassos-addons#42]
I always wanted to explore timescaledb but never had a good use case for it. 

Now I noticed this add-on so I can link my home assistant resource to it but I was wondering if it is possible without moving away from the current database before making this big step? 

Is it possible to continuously pull data from home assistant instead of ditching the database that I am currently using?

**Comment by expaso** [comment]
Yeah sure!

1)  Install this addon, add LTSS, and point that one to Timescale.
2)  Leave the connection of the home-assisstant recorder unchanged.

This way, LTSS is just a 'secondary recorder', where you can do your timescale stuff, and the original recorder is just what it it now.

**Comment by jjkoehorst** [comment]
Awesome thanks! That works like a charm, btw is there a config option to allow network access to TimescaleDB as currently it is only possible through pgadmin within home assistant and I would like to see / test to program against it.

**Comment by expaso** [comment]
My pleasure!

You can open-up the addon to the outside world using the network panel within the addon-configuration screen:

![image](https://github.com/Expaso/hassos-addons/assets/26247804/7aa63b0e-9b0b-40fd-8ece-39c608000239)
