### ISSUE TITLE
Paste from macOS clipboard not working within pgadmin SQL window

### ISSUE THREAD

**Issue by 42Network** [Expaso/hassos-addons#43]
Hi. Thanks for the suggestion and sorry for the delay. I made mine look like yours, using port 12346, and saved and restarted pgAdmin (a few times). However, trying to browse to that new port( homeassistant:12346) fails, and when I use "Open Web UI" from within the pgAdmin Addon, it still opens pgAdmin at the default URL of homeassistant:8123/hassio/ingress/77b2833f_pgadmin4. Also, when I view the YAML version of the pgAdmin config, this new custom port is not mentioned. Somehow it isn't sticking...ideas?

_Originally posted by @42Network in https://github.com/Expaso/hassos-addons/issues/40#issuecomment-2062071572_

**Comment by 42Network** [comment]
Found a fix at [this link](https://www.postgresql.org/message-id/839222cb-c105-4fb1-9243-d204a51ec924%40thuenen.de)

```
1.Type*chrome://flags/#unsafely-treat-insecure-origin-as-secure*in the 
address bar.
Add the origin which you need to treat as secure as shown in the below 
image.



2.On your computer, open Chrome.
Navigate to chrome*Settings*.
Click*Privacy and security* > *Site settings*.
Select the setting you want to update.
In *Permissions* section, click on *Additional Permissions*.
Open *Clipboard* settings.
Click on the Add button beside Allowed to see your clipboard section and 
add your pgAdmin 4 url.
```

**Comment by 42Network** [comment]
See [here](https://www.postgresql.org/message-id/839222cb-c105-4fb1-9243-d204a51ec924%40thuenen.de) for resolution.

**Comment by expaso** [comment]
Wow! Who have thought of that! Thank you, and I'm glad it works for you now!
