### ISSUE TITLE
Timescaledb 32 bit arm compatibility

### ISSUE THREAD

**Issue by berga** [Expaso/hassos-addons#5]
Hi, I'm using hassio on latest raspbian like distro (hypriot os on raspberry pi 4 with 4Gb ram and SSD boot)
would it be weird to compile this add-on for 32 bit arch too?

I could help to compile and test it

**Comment by expaso** [comment]
Hi @berga! I tried to compile it for armv7, but some parts of it just wouldn't cross-compile. If you could give me a hand with that, I will be gratefull!

See this revert-commit: https://github.com/Expaso/hassos-addon-timescaledb/commit/c65d0f6f265221a315972b79f0d9b87425695ceb for details

I am running this myself on a RPI4 with 4GB (and it runs great!) , but I use the 64-bit HassOS image from homeassistant itself, so I never had the need to support 32 bit, and decided not to invest too much time in that.

Maybe I was also a bit afraid that people would try to run it on a RPI3 with 1GB mem, and bring themselves into trouble.

What is your opinion?

**Comment by berga** [comment]
I've built the image directly on Raspi, pushed to my hub (berga/hassos-addon-timescaledb-armv7), tested locally and pushed the fix for Dockerfile, I hanven't touched the .github/workflows/ci.yml file.

About RPI3 I think that a Warning or a Requirements section on the README would be enough.

**Comment by expaso** [comment]
Hmm.. I see that certain packages are now available for alpine which were non-exisiting at the time.
I will revisit the ARMv7 compatibility. Thanks for bringing it up!

**Comment by expaso** [comment]
Follow up: https://github.com/Expaso/hassos-addon-timescaledb/issues/7
